### ISSUE TITLE
Python 3 support???

### ISSUE THREAD

**Issue by iwuvjhdva** [tomashanacek/mock-server#12]
Are there any plans on supporting Python 3?
Thanks!

**Comment by davidmankin** [comment]
For my case, I'm running unit tests which want to start up mock-server. But the unit tests run in a virtualenv which only provides python3 so it's easiest of mock-server supports python3 too.

**Comment by stephanepechard** [comment]
@iwuvjhdva @davidmankin @tomashanacek 
Just [committed](https://github.com/stephanepechard/mock-server) a fork that tries to be usable with Python 3.6. Not tested thoroughly yet, but works for me on major use cases. Will try to fix most problems when I encounter them.

**Comment by tomashanacek** [comment]
Hi, I just released a new version 0.3.9, it should also fix this issue. Feel free to reopen if not.
