### ISSUE TITLE
not able to install using "easy_install mock-server" throwing error 

### ISSUE THREAD

**Issue by srthorat** [tomashanacek/mock-server#28]
root@ubuntu:~/rest# easy_install mock-server
Searching for mock-server
Reading https://pypi.python.org/simple/mock-server/
Download error on https://pypi.python.org/simple/mock-server/: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed -- Some packages may not be found!
Couldn't find index page for 'mock-server' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed -- Some packages may not be found!
No local packages or download links found for mock-server
error: Could not find suitable distribution for Requirement.parse('mock-server')

**Comment by srthorat** [comment]
also with pip install mock-serve

root@ubuntu:~/rest# pip install mock-server
Downloading/unpacking mock-server
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement mock-server
Cleaning up...
No distributions at all found for mock-server
Storing debug log for failure in /root/.pip/pip.log

**Comment by kelvintaywl** [comment]
I was able to pip install the package successfully though
if the details help:

- ubuntu 14.01
- python3

**Comment by krmaxwell** [comment]
Is this still an issue? Seems to install correctly at this point.

**Comment by kelvintaywl** [comment]
@tomashanacek I think we can close this issue? :)
